CREATE TABLE account (
	id BIGINT(20) AUTO_INCREMENT,
	number VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL,
  owner_id VARBINARY(36) NOT NULL,
  balance DECIMAL(19,2) NOT NULL,
  update_date DATETIME DEFAULT NULL,
  active BIT(1) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
