server:
  port: 8086

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    database: MYSQL
    show-sql: true
  cache:
    type: redis
    cache-null-values: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
      ssl:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
    operationsSorter: method
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

external:
  users-api:
    url: https://internal-banking/users-api
  bacen-api:
    url: https://bacen-developer.com.br/notifications

cache:
  config:
    entryTtl: 60
    account:
      entryTtl: 30
