server:
  port: 8086

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    database: MYSQL
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
    operationsSorter: method
